Add: Add Push Notification
sparcs-kaist/taxi-app pull request #11
Opened 2022-08-17 13:21 UTC by happycastle114

# Summary 

Firebase를 활용한 푸시 알림 기능 추가

It closes #10 

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

# Further Work 

- Do something...

2022-09-13 13:23 UTC, happycastle114 commented
Android에서 Push가 안와서 어떻게 고쳐야하나 고민했는데..
KAIST WIFI 문제였던 것 같습니다..ㅜㅜ 개인핫스팟으로 변경하니 제대로 푸시가 옵니다..!!

2022-09-13 13:29 UTC, happycastle114 commented
@sboh1214 그리고 APN 인증서가 필요합니다! 혹시 동아리 애플 개발자 계정이 있을까요?

2022-09-13 14:23 UTC, 14KGun approved these changes

2022-09-14 07:36 UTC, sboh1214 requested changes
`lib/firebase_options.dart` file이 보이지 않는데 다음 링크를 참고하셔서 firebase를 연결하시는 것이 좋을 것 같습니다.
https://firebase.google.com/docs/flutter/setup

2022-09-14 07:36 UTC, sboh1214 commented on android/app/build.gradle
> +        minSdkVersion  28 // flutter.minSdkVersion
minSdkVersion이 너무 높습니다. otl-app 같은 경우 21로 하고 있습니다.

2022-09-14 07:36 UTC, sboh1214 commented on pubspec.yaml
> +  firebase_core: any
특별한 이유가 없으면 버전을 명시적으로 지정해주시기 바랍니다.

2022-09-20 04:33 UTC, happycastle114 commented
> `lib/firebase_options.dart` file이 보이지 않는데 다음 링크를 참고하셔서 firebase를 연결하시는 것이 좋을 것 같습니다. https://firebase.google.com/docs/flutter/setup

혹시 firebase_options.dart 파일에 들어있는 api 키 등은 공개되도 괜찮은 키일까요? 아니면 .gitignore에 등록해야하는 파일일까요?
그리고 firebase_options.dart의 파일이 어떤 기능을 할까요? 대충 살펴본 결과 이미 설정된 플랫폼 외에서 Firebase를 구성하려 할 경우에 에러를 띄우는 것 같은데, 제가 이해한 것이 맞을까요?

2022-09-20 08:13 UTC, sboh1214 commented
> > `lib/firebase_options.dart` file이 보이지 않는데 다음 링크를 참고하셔서 firebase를 연결하시는 것이 좋을 것 같습니다. https://firebase.google.com/docs/flutter/setup
> 
> 혹시 firebase_options.dart 파일에 들어있는 api 키 등은 공개되도 괜찮은 키일까요? 아니면 .gitignore에 등록해야하는 파일일까요? 그리고 firebase_options.dart의 파일이 어떤 기능을 할까요? 대충 살펴본 결과 이미 설정된 플랫폼 외에서 Firebase를 구성하려 할 경우에 에러를 띄우는 것 같은데, 제가 이해한 것이 맞을까요?

본 링크를 참고하시면 Firebase API키는 공개되어도 괜찮습니다.

https://stackoverflow.com/questions/71432691/flutter-should-firebase-options-dart-be-added-to-gitignore

firebase_options 자체는 앱에서 firebase를 초기화할때 설정을 담고 있고,
말씀해주신 기능도 할 것 같습니다.
추가적으로 `flutterfire configure` 명령어를 실행하는 것이 해당 파일 생성 뿐만 아니라,
firebase 프로젝트 검증도 함께 진행하는 것으로 알고 있습니다.

2022-09-20 10:33 UTC, happycastle114 commented
> > > `lib/firebase_options.dart` file이 보이지 않는데 다음 링크를 참고하셔서 firebase를 연결하시는 것이 좋을 것 같습니다. https://firebase.google.com/docs/flutter/setup
> > 
> > 
> > 혹시 firebase_options.dart 파일에 들어있는 api 키 등은 공개되도 괜찮은 키일까요? 아니면 .gitignore에 등록해야하는 파일일까요? 그리고 firebase_options.dart의 파일이 어떤 기능을 할까요? 대충 살펴본 결과 이미 설정된 플랫폼 외에서 Firebase를 구성하려 할 경우에 에러를 띄우는 것 같은데, 제가 이해한 것이 맞을까요?
> 
> 본 링크를 참고하시면 Firebase API키는 공개되어도 괜찮습니다.
> 
> https://stackoverflow.com/questions/71432691/flutter-should-firebase-options-dart-be-added-to-gitignore
> 
> firebase_options 자체는 앱에서 firebase를 초기화할때 설정을 담고 있고, 말씀해주신 기능도 할 것 같습니다. 추가적으로 `flutterfire configure` 명령어를 실행하는 것이 해당 파일 생성 뿐만 아니라, firebase 프로젝트 검증도 함께 진행하는 것으로 알고 있습니다.

답변해주셔서 감사합니다 :) 추가하였습니다..!!

2022-09-21 06:14 UTC, sboh1214 approved these changes
LGTM

2022-09-21 10:58 UTC, merged