Add: auto login improvement
sparcs-kaist/taxi-app pull request #20
Opened 2022-11-16 20:41 UTC by happycastle114

# Summary 

토큰 기반 자동로그인 기능 추가

It closes #14 

# Extra info 

# Images or Screenshots 

# Further Work 

- 로그인 페이지 디자인 개선

2022-11-17 04:27 UTC, sboh1214 requested changes

2022-11-17 04:27 UTC, sboh1214 commented on lib/views/taxiView.dart
> +        Token().getSession().then((value) async {
이것도 code style 정하는 문제인데, await 과 promise를 섞은 코드는 읽기 불편할 수도 있습니다

2022-11-17 05:07 UTC, happycastle114 commented on lib/constants/constants.dart
>    connectTimeout: 15000,
딱히 의도된 부분은 아닙니다....ㅠㅠ 어디서 코드 긁어보다가 가져온거 같은데..

2022-11-17 05:08 UTC, happycastle114 commented on lib/main.dart
>    // 사용자가 푸시 알림을 허용했는지 확인
위 쪽에 권한요청을 하는 것은데, 하나보니 아래로 내려왔나 봅니다 수정했습니다 :)

2022-11-17 05:09 UTC, happycastle114 commented on lib/main.dart
>    await dotenv.load(fileName: ".env");
어... 그러면 혹시 가장 먼저 실행이 되나요...?

2022-11-17 05:11 UTC, happycastle114 commented on lib/utils/token.dart
> +    if (accessToken == null) {
아.. 이것은 제가 ??의 존재를 모르고 있을 때 쓴거라 그렇습니다..! 수정하겠습니다 :)

2022-11-17 05:12 UTC, happycastle114 commented on lib/utils/token.dart
> +    if (accessToken == null) {
private 변수로 사용할 예정이라 수정했습니다..!

2022-11-17 05:16 UTC, happycastle114 commented on lib/utils/token.dart
> +  Future<void> setAccessToken({required String accessToken}) async {
accessToken과 refreshToken을 따로 변화시킬 시나리오가 있을 줄 알았는데 생각해보니 없네요.. 수정하겠습니다 :)

2022-11-17 05:16 UTC, happycastle114 commented on lib/views/loginView.dart
> +    final callbackUrlScheme = "org.sparcs.taxiApp";
딱히 없습니다! taxi에서 camelCase를 사용한다고 해서 그렇게 설정해둔거라..!!

2022-11-17 05:18 UTC, happycastle114 commented on lib/views/taxiView.dart
> +        Token().getSession().then((value) async {
useEffect에서 사용하는 함수는 async를 사용할 수 없다고 해서 이렇게 설정해두었는데.. 다른 방법이 있을까요..?

2022-11-17 07:13 UTC, happycastle114 commented on lib/views/loginView.dart
> +    final callbackUrlScheme = "org.sparcs.taxiApp";
https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore

요런 이유로 underscore를 추가하지 않았습니다.

2022-12-05 01:48 UTC, sboh1214 commented on lib/main.dart
>    await dotenv.load(fileName: ".env");
아마 그럴겁니다

2022-12-05 01:48 UTC, sboh1214 commented on lib/constants/constants.dart
>    connectTimeout: 15000,
기본 설정으로 해보고 문제가 있다면 바꾸는 것이 좋을 것 같습니다.

2022-12-05 01:49 UTC, sboh1214 commented on lib/views/loginView.dart
> +    final callbackUrlScheme = "org.sparcs.taxiApp";
package name 이 taxiapp이라면 통일하는 것이 좋을 것 같습니다.

2022-12-05 01:50 UTC, sboh1214 commented on lib/views/taxiView.dart
> +        Token().getSession().then((value) async {
저같은 경우에는 함수를 따로 파서
```
useEffect(() => {
   asyncFunction()
}, [])
```
과 같이 작성합니다

2022-12-05 01:50 UTC, sboh1214 approved these changes
LGTM

2022-12-05 04:17 UTC, merged