Add: 사용자에게 업데이트 요구
sparcs-kaist/taxi-app pull request #38
Opened 2023-02-28 14:47 UTC by happycastle114

# Summary 

It closes #31

# Extra info 

# Images or Screenshots 

# Further Work 

- Do something...

2023-03-21 11:00 UTC, 14KGun approved these changes
👍

2023-03-21 11:00 UTC, 14KGun commented on lib/firebase_options.dart
> +    iosBundleId: 'org.sparcs.taxi_app-app',
`app` text 중복되는 거 맞나요??

2023-03-21 12:41 UTC, happycastle114 commented on lib/firebase_options.dart
> +    iosBundleId: 'org.sparcs.taxi_app-app',
수정했습니다 :)

2023-03-21 19:31 UTC, sboh1214 requested changes

2023-03-21 19:31 UTC, sboh1214 commented on pubspec.yaml
> +  launch_review: ^3.0.1
https://github.com/Purus/launch_review#ios

iOS에서 추가적인 설정이 필요한 라이브러리로 보입니다.

2023-03-21 19:31 UTC, sboh1214 commented on lib/views/taxiDialog.dart
> +                  style: GoogleFonts.roboto(
모든 Text에 Roboto 폰트를 사용한다면, 앱 테마 폰트를 Roboto로 바꾸는 것이 좋을 거 같아요
출처: https://pub.dev/packages/google_fonts

```dart
...
  return MaterialApp(
    theme: _buildTheme(Brightness.dark),
  );
}

ThemeData _buildTheme(brightness) {
  var baseTheme = ThemeData(brightness: brightness);

  return baseTheme.copyWith(
    textTheme: GoogleFonts.latoTextTheme(baseTheme.textTheme),
  );
}
```

2023-03-21 19:32 UTC, sboh1214 commented
@happycastle114 아 그리고 PR 설명에 사용자에게 리뷰를 요청하는 기능도 추가되었다고 써주면 좋을 것 같아요

2023-04-03 12:16 UTC, happycastle114 commented on pubspec.yaml
> +  launch_review: ^3.0.1
수정했습니다 :)

2023-04-04 01:02 UTC, happycastle114 commented on lib/views/taxiDialog.dart
> +                  style: GoogleFonts.roboto(
텍스트가 사용되는 곳이 해당 위젯 말고는 없어서, 별도로 세팅 해주지는 않았습니다.

2023-04-04 04:12 UTC, happycastle114 commented on lib/views/taxiDialog.dart
> +                  style: GoogleFonts.roboto(
이후, 텍스트가 더 추가된다면 추가하도록 하겠습니다 :)

2023-04-04 04:14 UTC, happycastle114 commented
> @happycastle114 아 그리고 PR 설명에 사용자에게 리뷰를 요청하는 기능도 추가되었다고 써주면 좋을 것 같아요

리뷰를 요청하기보다는, 리뷰는 부수적이고 사용자에게 업데이트를 요구하기 위해 해당 라이브러리를 사용했습니다 :)

2023-04-04 08:01 UTC, sboh1214 approved these changes

2023-04-04 11:22 UTC, 14KGun approved these changes
👍

2023-04-04 12:12 UTC, merged