Add: Push Navigation
sparcs-kaist/taxi-app pull request #40
Opened 2023-03-21 10:13 UTC by happycastle114

# Summary 

It closes #34 

# Extra info 

# Images or Screenshots 

# Further Work 

- Do something...

2023-04-04 02:44 UTC, 14KGun commented on lib/main.dart
> +  print(FcmToken().token);
지워도 되지 않나요?

2023-04-04 02:44 UTC, 14KGun commented on lib/views/taxiView.dart
> +                    }
처음 로그인 페이지로 돌아가는 것은 웹 뷰의 역할 인거죠?

2023-04-04 04:09 UTC, happycastle114 commented on lib/main.dart
> +  print(FcmToken().token);
아 잊어버리고 못 지웠네요 ㅜㅜ 수정하겠습니다 :)

2023-04-04 04:10 UTC, happycastle114 commented on lib/views/taxiView.dart
> +                    }
isAuthLogin value가 False면 로그인 페이지를 띄웁니다..!

2023-04-05 03:20 UTC, 14KGun approved these changes
👍

2023-04-05 03:21 UTC, 14KGun commented on lib/views/taxiView.dart
> +                    }
오옹 이해했습니다. 다만 로그인 필수 조건을 지웠을 때 어떻게 대처할지 고민해봐야겠네요!!

2023-04-05 04:33 UTC, sboh1214 requested changes

2023-04-05 04:33 UTC, sboh1214 commented on lib/utils/pushHandler.dart
> +  var channel = const AndroidNotificationChannel(
이쪽 변경 사항이 없는 상수들은 final 이 좋을 것 같아요

2023-04-05 04:33 UTC, sboh1214 commented on android/app/src/main/AndroidManifest.xml
> +            <meta-data
이건 어떤 데이터인가요? 설명이 있다면 좋을 것 같아요

2023-04-05 04:33 UTC, sboh1214 commented on lib/views/loginView.dart
> +    const callbackUrlScheme = "org.sparcs.taxiapp";
url scheme 구조상 taxi_app 이 안된거 같은데, 나중에 헷갈릴 여지가 있겠습니다.

2023-04-05 04:33 UTC, sboh1214 commented on lib/views/taxiView.dart
> +  TaxiView();
이 코드는 어떤 역할인가요?

2023-04-05 04:33 UTC, sboh1214 commented on lib/views/taxiView.dart
> +          .then((NotificationAppLaunchDetails? details) {
이쪽만 then을 사용한 이유가 있나요?
아 useEffect 안에서는 async가 안되나 보네요

2023-04-05 04:33 UTC, sboh1214 commented on lib/views/taxiView.dart
> +      var initializationSettingsAndroid =
마찬가지로 final 일 수 있는 상수는 표시해주면 추후에 코드 읽기 좋을 것 같습니다

2023-04-05 04:33 UTC, sboh1214 commented on lib/views/taxiView.dart
> +    final isFirstLoaded = useState(0);
변수의 이름(is로 시작하는 boolean)과 실제 변수 타입(int)이 맞지 않습니다.
더 좋은 이름이 있을까요?

2023-04-05 16:15 UTC, happycastle114 commented on lib/views/taxiView.dart
> +          .then((NotificationAppLaunchDetails? details) {
아 네네 async를 사용할 수 없어서, 이렇게 사용했습니다 :)

2023-04-06 04:21 UTC, happycastle114 commented on lib/views/taxiView.dart
> +  TaxiView();
원래 TaxiView 생성자 안에 init_url를 받아왔었는데, 해당 부분을 삭제하면서 생성자를 지우지 않았네요.. 수정했습니다..!

2023-04-06 04:21 UTC, happycastle114 commented on lib/views/loginView.dart
> +    const callbackUrlScheme = "org.sparcs.taxiapp";
org.sparcs.taxiapp을 제 play console에 등록해버려서 사용하지 못했습니다..ㅜㅜ

2023-04-06 04:24 UTC, happycastle114 commented on android/app/src/main/AndroidManifest.xml
> +            <meta-data
Flutter inappwebview에서 설정을 해줘야한다고 해서 추가한 값입니다 :)

2023-04-06 07:06 UTC, sboh1214 approved these changes

2023-04-06 12:49 UTC, merged