Add: Auto Login Using
sparcs-kaist/taxi-app pull request #7
Opened 2022-07-06 18:12 UTC by happycastle114

세션 쿠키를 활용한 자동 로그인 기능 추가

# Summary #6 

세션을 활용한 자동 로그인 기능 추가

# Extra info 

- Needs more than 2 reviewers? y
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Further Work

2022-07-08 07:49 UTC, 14KGun requested changes

2022-07-08 07:49 UTC, 14KGun commented on pubspec.yaml
> +description: A new Flutter project.
추후 변경이 필요해 보입니다

2022-07-08 07:49 UTC, 14KGun commented on pubspec.yaml
> +  #         weight: 700
Taxi의 기본 폰트는 NanumSquare 입니다.
https://github.com/sparcs-kaist/taxi-front/tree/main/src/fonts

2022-07-08 07:49 UTC, 14KGun commented on lib/utils/auth.dart
> +  String address = dotenv.get("BACKEND_ADDRESS");
.env 파일에 대한 정리 문서가 필요해보입니다.
https://github.com/sparcs-kaist/taxi-front/blob/main/.env.example
참고해주세요

2022-07-08 08:57 UTC, 14KGun commented on pubspec.yaml
> +  #         weight: 700
폰트 관련 파일은 프론트 깃에서 가져오시면 될 것 같고,
나중에 이슈 만드셔서 따로 작업하셔도 될 것 같아요!

2022-07-08 08:58 UTC, 14KGun commented on lib/utils/auth.dart
> +  String address = dotenv.get("BACKEND_ADDRESS");
위 예시와 같이 .env.example 파일 만드시면 될 것 같아요

2022-07-08 09:09 UTC, happycastle114 commented on lib/utils/auth.dart
> +  String address = dotenv.get("BACKEND_ADDRESS");
아 넵 sample 파일을 만들어두었었는데 사라졌나보네요! 작성해두겠습니다!

2022-07-08 09:10 UTC, happycastle114 commented on pubspec.yaml
> +  #         weight: 700
아 넵 알겠습니다. 추가하겠습니다.

2022-07-09 01:52 UTC, sboh1214 commented
프로젝트 생성하실때 android, iOS 프로젝트도 같이 생기지 않나요?
추후에 생성하실 때 package name은 org.sparcs.* 으로 하시면 될 것 같습니다. iOS 학교 계정 프로파일은 요청하시면 DM으로 보내 드릴게요

2022-07-14 03:05 UTC, sboh1214 requested changes
몇군데 누락된 곳들에서 android package name 동일하게 변경 요청드렸습니다.
그리고, flutter webview로 flutter_inappwebview 선택하셨는데
현재 안드로이드에서 키보드가 나오지 않는 문제가 있습니다.
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1083 
참고하셔서 option 설정하시거나 webview_flutter 사용을 추천드립니다.

2022-07-14 06:47 UTC, happycastle114 commented
> 몇군데 누락된 곳들에서 android package name 동일하게 변경 요청드렸습니다. 그리고, flutter webview로 flutter_inappwebview 선택하셨는데 현재 안드로이드에서 키보드가 나오지 않는 문제가 있습니다. [pichillilorenzo/flutter_inappwebview#1083](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1083) 참고하셔서 option 설정하시거나 webview_flutter 사용을 추천드립니다.

Package Name 수정하였고
Option 추가해서 수정하였습니다.

감사합니다.

2022-07-14 07:12 UTC, sboh1214 approved these changes

2022-07-21 17:34 UTC, happycastle114 commented on pubspec.yaml
> +description: A new Flutter project.
@14KGun 확인하시고 Approve 부탁드립니다!

2022-08-03 05:45 UTC, 14KGun requested changes
수고하셨습니다. 늦은 리뷰 죄송합니다 ㅜㅜ

2022-08-03 05:45 UTC, 14KGun commented on lib/utils/auth.dart
> +    print(response.statusCode);
지우셔야 할것 같아요

2022-08-03 05:45 UTC, 14KGun commented on lib/views/taxiView.dart
> +                print("SESSION TOKEN UPDATED!");
test용으로 사용하신 print는 최종 PR에서 지우셔야 합니다

2022-08-03 05:45 UTC, 14KGun commented on lib/utils/auth.dart
> +  );
이러한 코드들은 중복될 일이 많기 때문에 모듈화 되어있으면 좋을 것 같아요

2022-08-03 05:45 UTC, 14KGun commented on lib/utils/auth.dart
> +    return false;
함수 안에서 return이 있는데,
dart에서 try catch나 Promise함수는 사용이 불가능 한가용??
또한 catchError안에서의 return도 제기능을 하는지 궁금합니다.

2022-08-03 05:45 UTC, 14KGun commented on lib/views/taxiView.dart
> +  final _storage = FlutterSecureStorage();
taxi에서는 특수한 경우를 제외하고는 camelCase로 변수 명을 지정하셔야합니다.!!
dart에서도 camelCase를 사용하는지 모르겠는데,
변수명이 _로 시작하는 특별한 이유가 있나요???

2022-08-03 05:45 UTC, 14KGun commented on lib/views/taxiView.dart
> +            if (sessionToken == null) {
if (!sessionToken) 으로 줄일 수 있을 것 같아요

2022-08-03 05:45 UTC, 14KGun commented on lib/views/taxiView.dart
> +            String? sessionToken = await _storage.read(key: "sessionToken");
_storage.read(key: "sessionToken");가 에러가 나는 상황은 없나요??
try catch가 안보이네요

2022-08-04 02:35 UTC, sboh1214 commented on lib/views/taxiView.dart
> +  final _storage = FlutterSecureStorage();
dart에서 class의 private 변수는 _을 붙이는 것으로 알고 있습니다.
https://stackoverflow.com/questions/17488611/how-to-create-private-variables-in-dart

2022-08-08 12:17 UTC, 14KGun approved these changes
수고하셨습니다~~~
첫 PR 축하드립니다 ~~😃😃🚕🚕

2022-08-08 12:19 UTC, merged